import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google';
import { ThemeProvider } from "@/components/theme-provider"
import LeftNav from "@/components/LeftNav";


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-gray-900 text-gray-800 ${inter.className}`}>
    <body className="flex  ">
      <main className="flex-grow"> 
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
            {children}
        </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
